id: P009506
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16558
  title: གསུང་འབུམ། ངག་དབང་པདྨ་རྣམ་རྒྱལ།
  author: ''
  volumes:
    51eb82cc6c8a4913b211103306cb56d1:
      image_group_id: I2PD18378
      title: ''
      volume_number: 1
      total_pages: 266
      base_file: v001.txt
